# Generated by Django 4.2.8 on 2023-12-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="leader_email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="leader_email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
    ]
