# Generated by Django 4.2.8 on 2023-12-12 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leader", "0003_alter_person_leader_email_alter_team_leader_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="leader_email",
            new_name="_user",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="leader_email",
            new_name="_user",
        ),
    ]
