# Generated by Django 4.2.8 on 2023-12-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leader", "0004_rename_leader_email_person__user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_supervisor",
            field=models.BooleanField(default=False),
        ),
    ]
