# Generated by Django 4.2.8 on 2023-12-12 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("org", "0002_alter_event_options"),
        ("leader", "0005_person_is_supervisor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name": "Team", "verbose_name_plural": "Teams"},
        ),
        migrations.AlterField(
            model_name="person",
            name="phone_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="supervisor",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="leader.person"),
        ),
        migrations.RemoveField(
            model_name="team",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="team",
            name="competitors",
        ),
        migrations.AlterField(
            model_name="team",
            name="team_leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="leader", to="leader.person"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="categories",
            field=models.ManyToManyField(to="org.category"),
        ),
        migrations.AddField(
            model_name="team",
            name="competitors",
            field=models.ManyToManyField(to="leader.person"),
        ),
    ]
