# Generated by Django 4.2.8 on 2023-12-12 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leader", "0006_alter_team_options_alter_person_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="supervisor",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="leader.person"
            ),
        ),
    ]
