# Generated by Django 4.2.8 on 2023-12-18 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leader", "0006_alter_team_options_alter_person_phone_number"),
        ("leader", "0007_alter_person_supervisor"),
    ]

    operations = []
