# Generated by Django 4.2.8 on 2023-12-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leader", "0008_merge_20231218_0916"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="birth_date",
            field=models.DateField(),
        ),
    ]
