# Generated by Django 4.2.8 on 2023-12-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leader", "0012_rename__user_person_user_rename__user_team_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="diet",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="person",
            name="primary_school",
            field=models.BooleanField(default=False),
        ),
    ]
