# Generated by Django 4.2.8 on 2024-01-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leader", "0013_alter_person_diet_alter_person_primary_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
