# Generated by Django 4.2.9 on 2024-01-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leader", "0014_alter_person_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="checked_in",
            field=models.BooleanField(default=False),
        ),
    ]
