# Generated by Django 4.2.9 on 2024-01-23 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="robocupuser",
            managers=[],
        ),
    ]
