# Generated by Django 4.2.8 on 2023-12-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('birth_date', models.DateTimeField()),
                ('primary_school', models.BooleanField()),
                ('diet', models.CharField(default='Ziadna', max_length=100)),
                ('accomodation1', models.BooleanField(default=True)),
                ('accomodation2', models.BooleanField(default=True)),
                ('food1', models.BooleanField(default=True)),
                ('food2', models.BooleanField(default=True)),
                ('food3', models.BooleanField(default=True)),
                ('supervisor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('order', models.CharField(max_length=100)),
            ],
        ),
    ]
