# Generated by Django 4.2.8 on 2023-12-05 13:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_person_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('team_leader', models.IntegerField()),
                ('organization', models.CharField(max_length=100)),
                ('competitors', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('category', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
