# Generated by Django 4.2.9 on 2024-01-23 10:05

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("place", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("registration_start_date", models.DateField()),
                ("registration_end_date", models.DateField()),
                ("registration_open", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("team_name", models.CharField(max_length=100)),
                ("order", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("primary_school", models.CharField(default=True)),
                ("list_of_results", models.CharField(max_length=100)),
                ("soccer", models.BooleanField(default=False)),
                ("group_size", models.IntegerField(default=4)),
                ("advance", models.IntegerField(default=2)),
                ("ranking_params", models.CharField(max_length=100)),
                ("results", jsonfield.fields.JSONField(blank=True, null=True)),
                ("event", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="org.event")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(fields=("name", "event"), name="unique_name_event"),
        ),
    ]
