# Generated by Django 4.2.8 on 2023-12-05 18:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("primary_school", models.CharField(default=True)),
                ("list_of_results", models.CharField(max_length=100)),
                ("soccer", models.BooleanField(default=False)),
                ("group_size", models.IntegerField(default=4)),
                ("advance", models.IntegerField(default=2)),
                ("ranking_params", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("place", models.CharField(max_length=100)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("registration_start_date", models.DateTimeField()),
                ("registration_end_date", models.DateTimeField()),
                ("registration_open", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("categories", django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
    ]
