# Generated by Django 4.2 on 2024-03-04 16:28

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('place', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_start_date', models.DateField()),
                ('registration_end_date', models.DateField()),
                ('registration_open', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('order', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('primary_school', models.CharField(choices=[('ZŠ', 'Základná škola'), ('V', 'Všetci')], default='ZŠ', max_length=2)),
                ('list_of_results', models.CharField(choices=[('BOTH', 'Both'), ('COMB', 'Combined'), ('SEPR', 'Seperate')], default='COMB', max_length=255)),
                ('results', jsonfield.fields.JSONField(blank=True, null=True)),
                ('detailed_pdf', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='org.event')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'event'), name='unique_name_event'),
        ),
    ]
