# Generated by Django 4.2.9 on 2024-02-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("org", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="advance",
        ),
        migrations.RemoveField(
            model_name="category",
            name="group_size",
        ),
        migrations.RemoveField(
            model_name="category",
            name="ranking_params",
        ),
        migrations.RemoveField(
            model_name="category",
            name="soccer",
        ),
        migrations.AddField(
            model_name="category",
            name="detailed_pdf",
            field=models.FileField(blank=True, null=True, upload_to="uploads/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="category",
            name="list_of_results",
            field=models.CharField(
                choices=[("BOTH", "Both"), ("COMB", "Combined"), ("SEPR", "Seperate")], default="COMB", max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="primary_school",
            field=models.CharField(
                choices=[("ZŠ", "Základná škola"), ("SŠ", "Stredná škola")], default="ZŠ", max_length=2
            ),
        ),
    ]
