# Generated by Django 4.2 on 2024-03-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='advancing_teams_per_group',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='is_soccer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='max_teams_per_group',
            field=models.IntegerField(default=0),
        ),
    ]
