# Generated by Django 4.2.8 on 2023-12-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("org", "0003_remove_event_categories_category_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateField(),
        ),
    ]
