# Generated by Django 4.2.9 on 2024-01-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0006_category_results"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(fields=("name", "event"), name="unique_name_event"),
        ),
    ]
