# Generated by Django 4.2.9 on 2024-01-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0007_category_unique_name_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
